# Generated by Django 4.2.11 on 2024-04-09 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_img',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
